name: Healthy Teams CI/CD

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.102
    
    - name: Restore with dotnet
      run: dotnet restore
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Test with dotnet
      run: dotnet test --configuration Release
    
    - name: Publish with dotnet
      run: dotnet publish HealthyTeams.Api/HealthyTeams.Api.csproj --output ./publish-output --configuration Release
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v1
      with: 
        app-name: healthyteams
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: /home/runner/work/intro-healthy-teams/intro-healthy-teams/publish-output
